{ spotify:
   { id: '8c19f6cb5a074bc5bd410898f400a56f',
     secret: '3430204f3a844a8ab2638a281e712c90' } }
8c19f6cb5a074bc5bd410898f400a56f
{ status: 200,
  statusText: 'OK',
  headers:
   { server: 'nginx',
     date: 'Tue, 30 Apr 2019 00:53:52 GMT',
     'content-type': 'text/html;charset=utf-8',
     'content-length': '855',
     connection: 'close',
     vary: 'Accept-Encoding',
     'x-frame-options': 'deny',
     'x-ua-compatible': 'IE=edge',
     'cache-control': 'no-cache, no-store, must-revalidate',
     pragma: 'no-cache',
     'content-security-policy':
      'default-src \'self\'; script-src \'self\' https://www.google-analytics.com https://www.google.com https://www.gstatic.com https://accounts.scdn.co; img-src \'self\' https://i.imgur.com https://d2mv8tnci56s9d.cloudfront.net https://profile-images.scdn.co https://ac
i.scdn.co https://graph.facebook.com https://fbcdn-profile-a.akamaihd.net https://scontent.xx.fbcdn.net https://platform-lookaside.fbsbx.com https://www.google-analytics.com https://stats.g.doubleclick.net data: https://accounts.scdn.co; font-src \'self\' https://sp-boot
strap.global.ssl.fastly.net https://fonts.gstatic.com; style-src \'self\' \'unsafe-inline\' https://accounts.scdn.co; frame-src \'self\' https://www.spotify.com https://www.google.com https://app.adjust.com https://itunes.apple.com itms-apps:;',
     'x-content-security-policy':
      'default-src \'self\'; script-src \'self\' https://www.google-analytics.com https://www.google.com https://www.gstatic.com https://accounts.scdn.co; img-src \'self\' https://i.imgur.com https://d2mv8tnci56s9d.cloudfront.net https://profile-images.scdn.co https://ac
i.scdn.co https://graph.facebook.com https://fbcdn-profile-a.akamaihd.net https://scontent.xx.fbcdn.net https://platform-lookaside.fbsbx.com https://www.google-analytics.com https://stats.g.doubleclick.net data: https://accounts.scdn.co; font-src \'self\' https://sp-boot
strap.global.ssl.fastly.net https://fonts.gstatic.com; style-src \'self\' \'unsafe-inline\' https://accounts.scdn.co; frame-src \'self\' https://www.spotify.com https://www.google.com https://app.adjust.com https://itunes.apple.com itms-apps:;',
     'set-cookie':
      [ 'csrf_token=AQA48W7oTobBCPSb4FF-wA87MX0CiehZJDoEPSyHlZv0DJ4qIKT5oKAGA4a5MXx4loOEXmLIKNd6WSf3;Version=1;Domain=accounts.spotify.com;Path=/;Secure' ],
     'x-content-type-options': 'nosniff',
     'strict-transport-security': 'max-age=31536000' },
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers:
      { Accept: 'application/json, text/plain, */*',
        'User-Agent': 'axios/0.18.0' },
     method: 'get',
     url:
      'https://accounts.spotify.com/authorize?client_id=8c19f6cb5a074bc5bd410898f400a56f&response_type=code&redirect_uri=https://github.com/mattpengelly/liri-node-app',
     data: undefined },
  request:
   ClientRequest {
     _events:
      [Object: null prototype] {
        socket: [Function],
        abort: [Function],
        aborted: [Function],
        error: [Function],
        timeout: [Function],
        prefinish: [Function: requestOnPrefinish] },
     _eventsCount: 6,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: false,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: 0,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'accounts.spotify.com',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 8,
        connecting: false,
        _hadError: false,
        _handle: [TLSWrap],
        _parent: null,
        _host: 'accounts.spotify.com',
        _readableState: [ReadableState],
        readable: true,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 21,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object] },
     connection:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'accounts.spotify.com',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 8,
        connecting: false,
        _hadError: false,
        _handle: [TLSWrap],
        _parent: null,
        _host: 'accounts.spotify.com',
        _readableState: [ReadableState],
        readable: true,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 21,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object] },
     _header:
      'GET /login?continue=https%3A%2F%2Faccounts.spotify.com%2Fauthorize%3Fclient_id%3D8c19f6cb5a074bc5bd410898f400a56f%26response_type%3Dcode%26redirect_uri%3Dhttps%253A%252F%252Fgithub.com%252Fmattpengelly%252Fliri-node-app HTTP/1.1\r\nAccept: application/json, text/p
lain, */*\r\nUser-Agent: axios/0.18.0\r\nHost: accounts.spotify.com\r\nConnection: close\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent:
      Agent {
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        maxCachedSessions: 100,
        _sessionCache: [Object] },
     socketPath: undefined,
     timeout: undefined,
     method: 'GET',
     path:
      '/login?continue=https%3A%2F%2Faccounts.spotify.com%2Fauthorize%3Fclient_id%3D8c19f6cb5a074bc5bd410898f400a56f%26response_type%3Dcode%26redirect_uri%3Dhttps%253A%252F%252Fgithub.com%252Fmattpengelly%252Fliri-node-app',
     _ended: true,
     res:
      IncomingMessage {
        _readableState: [ReadableState],
        readable: false,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        socket: [TLSSocket],
        connection: [TLSSocket],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        aborted: false,
        upgrade: false,
        url: '',
        method: null,
        statusCode: 200,
        statusMessage: 'OK',
        client: [TLSSocket],
        _consuming: false,
        _dumped: false,
        req: [Circular],
        responseUrl:
         'https://accounts.spotify.com/login?continue=https%3A%2F%2Faccounts.spotify.com%2Fauthorize%3Fclient_id%3D8c19f6cb5a074bc5bd410898f400a56f%26response_type%3Dcode%26redirect_uri%3Dhttps%253A%252F%252Fgithub.com%252Fmattpengelly%252Fliri-node-app',
        redirects: [] },
     aborted: undefined,
     timeoutCb: null,
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null,
     _redirectable:
      Writable {
        _writableState: [WritableState],
        writable: true,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _options: [Object],
        _ended: true,
        _ending: true,
        _redirectCount: 1,
        _redirects: [],
        _requestBodyLength: 0,
        _requestBodyBuffers: [],
        _onNativeResponse: [Function],
        _currentRequest: [Circular],
        _currentUrl:
         'https://accounts.spotify.com/login?continue=https%3A%2F%2Faccounts.spotify.com%2Fauthorize%3Fclient_id%3D8c19f6cb5a074bc5bd410898f400a56f%26response_type%3Dcode%26redirect_uri%3Dhttps%253A%252F%252Fgithub.com%252Fmattpengelly%252Fliri-node-app',
        _isRedirect: true },
     [Symbol(isCorked)]: false,
     [Symbol(outHeadersKey)]:
      [Object: null prototype] { accept: [Array], 'user-agent': [Array], host: [Array] } },
  data:
   '\n<!DOCTYPE html>\n<html id="app" lang="en" dir="ltr" ng-csp ng-strict-di>\n<head>\n  <meta charset="utf-8">\n  <title ng-bind="(&#39;loginTitle&#39; | localize) + &#39; - Spotify&#39;">Spotify</title>\n  <meta name="viewport" content="width=device-width, initial-sca
le=1.0, maximum-scale=1.0, user-scalable=no">\n  <base href="/">\n  <link rel="icon" href="https://accounts.scdn.co/images/favicon.ace4d8543bbb017893402a1e9d1ac1fa.ico">\n  <link href="https://accounts.scdn.co/css/index.8655209758bd23706121.css" media="screen" rel="style
sheet">\n\n  <script defer src="https://accounts.scdn.co/js/index.8655209758bd23706121.js" sp-bootstrap></script>\n  <meta ng-non-bindable sp-bootstrap-data=\'{"phoneFeatureEnabled":false,"user":false,"BON":["0","0",-161444399]}\'>\n</head>\n<body ng-controller="LoginCon
troller">\n  <div ng-include="template"></div>\n</body>\n</html>\n' }
